---
detectors:
  # Для математических операций можно повысить ограничение на максимальное количество операций
  # в методе и сделать его равным максимальному количеству строк в методе, заданному в конфигурации рубокопа.
  TooManyStatements:
    max_statements: 15